routes/web.php
<?php

// Auth
Auth::routes();

// Index
Route::get('/', 'HomeController@index')->name('home.index');

// real-estate pages
Route::group(['prefix' => 'real-estate'], function () {
    // Buildings
    Route::resource('buildings', 'BuildingController')->only('show', 'index');
    // Apartments
    Route::resource('apartments', 'ApartmentController')->only('show', 'index');
    // Search
    Route::get('search', 'HomeController@search')->name('search.index');

    // Static Pages
    Route::get('investments', 'HomeController@staticPage')->name('investments.index');
    Route::get('appraisals', 'HomeController@staticPage')->name('appraisals.index');
    Route::get('credits', 'HomeController@staticPage')->name('credits.index');
    Route::get('contact', 'HomeController@staticPage')->name('contact.index');
    Route::get('nosotros', 'HomeController@staticPage')->name('nosotros.index');
});

// Dashboard
Route::get('/dashboard', 'HomeController@dashboard')->middleware('auth');

// Amenities
Route::get('amenities', function(){
   return $items= App\Amenity::orderBy('title')->get();
})->name('amenity.list');

// Sliders
Route::post('save-sliders', 'SliderController@save');
Route::post('upload-sliders', 'SliderController@upload');
Route::get('get-sliders', 'SliderController@getApiSliders');
Route::delete('delete-sliders/{id}', 'SliderController@deleteSlide');

// Image uplooader route
Route::post('images-upload', 'ImageController@upload');


Route::group(['prefix' => 'developers'], function () {
    Route::get('/', 'ProjectController@index')->name('developers.index');
    Route::get('/{project}', 'ProjectController@show')->name('developers.show');
});

Route::group(['prefix' => 'houses'], function () {
    Route::get('/', 'HouseController@index')->name('houses.index');
    Route::get('/{house}', 'HouseController@show')->name('houses.show');
});

Route::group(['prefix' => 'articles'], function () {
    Route::get('/', 'ArticleController@index')->name('articles.index');
    Route::get('/{article}', 'ArticleController@show')->name('articles.show');
});

// excel read
route::post('import', 'ApartmentController@import');


// Mail
Route::post('/inquiry', 'HomeController@mail')->name('mail.contact');
Route::post('/inquiry/building/{building}', 'BuildingController@mail')->name('mail.buildings');
Route::post('/inquiry/apartments/{apartment}', 'ApartmentController@mail')->name('mail.apartments');
Route::post('/inquiry/developers', 'ProjectController@mail')->name('mail.developers');
Route::post('/inquiry/houses', 'HouseController@mail')->name('mail.houses');

// Fallback page
Route::get('/{path}',function() {
  return redirect('/dashboard');
})->where( 'path', '([A-z\d\-/_.]+)?' );

resources/views/real-estate/contact.blade.php
@extends('layouts.front')

@section('content')

<section class="appraisals-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
              <div class="appraisals-title">
                <h2>{{ $config['title'] }}</h2>
              </div>
               <div class="appraisals-bottom text-center">
                <p>{!! nl2br( $config['top_text'] ) !!}</p>
              </div>
                @if( $config['form'] === '1' )
                  @include ('partials.contact-form')
                @endif
                <div class="appraisals-bottom text-center">
                   <p>
                       {{ $config['bottom_text'] }}
                   </p>
                </div>
            </div>
        </div>
    </div>

</section>

@include('partials.front-footer')
@endsection

resources/views/real-estate/index.blade.php
@extends('layouts.front')

@section('content')

<section class="hero-area">
    @component('components.home-slider', [ 'slides'=> $slides,
                                           'section'=> 'real-estate' ])
        @include('components.search-area')
    @endcomponent
</section>

<section class="featured-properties-area my-10">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="project-title section-heading wow fadeInLeftBig">
                    <h2 id="real-estate_featured">Propiedades destacadas</h2>
                </div>
            </div>
        </div>
        <div class="row">

            {{-- Building box --}}
            @foreach ($buildings as $building)
            @include('building.box', ['building'=> $building ])
            @endforeach

        </div>


    </div>
</section>
<div id="apartments"></div>
<!-- ##### Propiedades en Venta Area End ##### -->

<!-- ##### Otras propiedades Area Start ##### -->
<section class="featured-properties-area section-padding-0-50">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="section-heading wow fadeInRightBig">
                    <h2 id="real-estate" class="text-uppercase">Propiedades</h2>
                </div>
            </div>
        </div>

        <div class="row">

            {{-- Apartment box --}}
            @foreach ($apartments as $apartment)
                @include('apartment.box', $apartment)
            @endforeach
        </div>
        <div class="row pull-right mr-3 paginadoHome">
            <div class="col-lg-1">{{ $apartments->links() }}</div>
        </div>
    </div>
    </div>
    <div class="">
        <div class="row logosUrbanFooter">
            <div class="col-4 colLogos">
                <a href="{{ route('home.index') }}" target="_blank"><img src="{{ asset('img/core-img/icLogoFooter1.png') }}" alt=""></a>
                    <p style="background:#007d3f;">PROPIEDADES</p>
                </div>
                <div class="col-4 colLogos">
                    <a href="{{ route('developers.index') }}" target="_blank"><img src="{{ asset('img/core-img/icLogoFooter2.png') }}" alt=""></a>
                    <p style="background:#b62126;">CONSTRUCTORA</p>
                </div>
                <div class="col-4 colLogos">
                    <a href="{{ route('houses.index') }}" target="_blank"><img src="{{ asset('img/core-img/icLogoFooter3.png') }}" alt=""></a>
                    <p style="background:#006fcb;">ARQUITECTURA</p>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Otras propiedades Area End ##### -->

    <!-- ##### Footer Area Start ##### -->
    @unless(request()->segment(1) === '')
        @include('partials.front-footer')
    @endunless

@endsection

resources/views/real-estate/investments.blade.php
@extends('layouts.front')

@section('content')

<section class="investments-page">

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="appraisals-title text-center">
                    <h2>{{ $config['title'] }}</h2>
                </div>
                <div class="appraisals-bottom text-center">
                    <p class="">{!! nl2br( $config['top_text']) !!}</p>
                </div>

                {{-- Formulario --}}
                @if( $config['form'] === '1' )
                <div id="formInvestments" class="col-xs-12">
                                @include ('partials.contact-form', ['btn_class' => 'pull-right'])
                            </div>
                @endif

                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="row">
                                @forelse ( $buildings as $building )
                                <div class="media m-2">
                                    <div class="media-body">
                                        <div class="container">
                                            <div class="row">
                                                <div class="col-md-3 media-left">
                                                    <a href="{{ route('buildings.show', $building->slug) }}"><img
                                                            class="thumbDetail"
                                                            src="{{ count($building->images) > 0 ? asset($building->images->first()->path) : '' }}"></a>
                                                </div>
                                                <div class="col-md-6 media-mid">
                                                    <div class="info-card">
                                                        <a href="{{ route('buildings.show', $building->slug) }}">
                                                            <h5 class="mt-0"> {{ $building->title }}</h5>
                                                        </a>
                                                        <p>{{ $building->address }}
                                                        </p>
                                                    </div>
                                                    <div class="details-card">
                                                        <p>{{ str_limit($building->description, 200, '...') }}</p>
                                                    </div>
                                                </div>
                                                <div class="col-md-3 media-right">
                                                    <div class="more-box">
                                                        <h5>Edificio</h5>
                                                        <div class="cta-more">
                                                            <a class="btn-more"
                                                                href="{{ route('buildings.show', $building->slug) }}">Ver
                                                                más</a>
                                                        </div>
                                                        {{-- <div class="deliver-box">
                                                            <h6>Entrega</h6>
                                                            <h6 class="deliver-date">Noviembre 2021</h6>
                                                        </div> --}}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                @empty
                                <div class="col-12">No existen edificios por el momento </div>
                                @endforelse

                            </div>
                            {{ $buildings->links() }}
                        </div>


                        <div class="appraisals-bottom text-center">
                            <p>
                                {{ $config['bottom_text'] }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

</section>

@include('partials.front-footer')

@endsection

resources/views/real-estate/nosotros.blade.php
@extends('layouts.front')

@section('content')


<section class="nosotros-page">
  <div class="HeaderNosotros">
    <img src="{{ asset('img/core-img/imgNosotros.jpg') }}" alt="Nosotros">
  </div>
  <div class="col-12 boxLaEmpresa">
    <h2 class="titNosotros">LA EMPRESA</h2>
    <p class="txtNosotros">Somos una empresa de trayectoria y vanguardia, con mas de 15 años de experiencia en el mercado, con fuerte impronta en negocios y desarrollos inmobiliarios. Llevamos adelante esta actividad con gran dedicación y profesionalismo, guardando los más altos estándares de excelencia, competitividad y ética profesional. Una empresa 100% responsable, con amplia experiencia laboral avocada a sus clientes,Hoy, al igual que en cada momento de nuestra trayectoria nuestros clientes nos eligen una y otra vez por ser sinónimo de profesionalismo, eficiencia y confiabilidad sumándole a ello nuestra actividad como desarrolladores de negocios inmobiliarios, cumpliendo ampliamente las expectativas de nuestros clientes. Nuestro crecimiento es constante, aprovechando lo ultimo en Tecnologia y Comunicación manteniéndonos en el mercado con una visión futura, actual y dinámica.</p>
  </div>
  <div class="col-12 boxLaEmpresaBottom">
      <p class="txtNosotros"> <img src="{{ asset('img/core-img/imgServicios.jpg') }}" align="right"  alt="Nosotros">Brindamos un conjunto de servicios con gran eficiencia acompañando al mercado y a las necesidades de cada cliente. Contamos con un equipo idóneo de profesionales para tasar el valor real de los inmuebles y establecer los criterios adecuados de cotización, respetando el patrimonio del cliente que nos confía su propiedad.
      </p>

      <p class="txtNosotros">
      Nos eligen porque ofrecemos gestión general en comercialización y marketing; prensa y publicidad en los medios más prestigiosos ya sea convencionales o actuales; diseño y desarrollo de la cartelería, gráfica y publicidad expandida; análisis, toma de acción y reporte de la gestión de marketing; concreción de metas; transparencia e Interacción permanente con cada cliente.
      </p>
      <p class="txtNosotros">
        <span class="font-bigger">Servicios</span><br>Brindamos un conjunto de servicios con gran eficiencia acompañando al mercado y a las
        necesidades de cada cliente. Contamos con un equipo idóneo de profesionales para tasar el valor real de los inmuebles y establecer los criterios adecuados de cotización, respetando el patrimonio del cliente que nos confía su propiedad.
      </p>

      <p class="txtNosotros">
        Nos eligen porque ofrecemos gestión general en comercialización y marketing; prensa y publicidad en los medios más prestigiosos ya sea convencionales o actuales; diseño y desarrollo de la cartelería, gráfica y publicidad expandida; análisis, toma de acción y reporte de la gestión de marketing; concreción de metas; transparencia e Interacción permanente con cada cliente.
      </p>
      <br>


      <p class="txtNosotros">
        <span class="font-bigger">Asesoramiento</span><br>  Otorgamos asesoramiento legal, comercial y financiero ya que consideramos de gran importancia brindar lo necesario en materia de soporte jurídico y contable al momento de la compra – venta de una propiedad. Estamos dispuestos a brindarle la mayor cantidad de herramientas, para que pueda tomar las mejores decisiones a la hora de concretar operaciones inmobiliarias.
      </p>

      <br><br>
  </div>

</section>

@include('partials.front-footer')

@endsection

resources/views/real-estate/search.blade.php
@extends('layouts.front')

@section('content')

<section class="container">
  <div class="row first-row">
      <div class="col-12">
          <div class="section-heading wow fadeIn">
              @if($apartments->count())
                <h4 class="my-4">{{ $apartments->count(). " ". Illuminate\Support\Str::plural('Resultado', $apartments->count()) }}
                                  para <span class="font-weight-bold">'@status_show($input->get('status'))'
                                  en <span class="font-weight-bold">'{{ $input->get('location') }}'</span></h4>
              @else
                <h2 class="my-4">{{ $apartments->count() }} Resultados</h2>
                <h3 class="my-4">No se hallaron propiedades</h3>

                      <a href="{{ route('home.index') }}" class="btn south-btn btn-4">Busca de nuevo &nbsp;<i class="fa fa-lg fa-search"></i></a>
              @endif
          </div>
      </div>
  </div>
</section>


{{-- <section id="real-estate" class="featured-properties-area section-padding-0-50">
  <div class="container">
      @forelse ( $apartments as $apartment)
        <div class="row">
          <div class="col-12 col-md-4 col-xl-4">
              <div class="single-featured-property other-properties mb-50 mt-5 wow fadeIn" data-wow-delay="100ms">
                  <!-- Property Thumbnail -->
                  <div class="property-thumb">
                      <a href="{{ route('apartments.show', $apartment->slug) }}">
                          <img src="{{ is_file($apartment->getImgPath($apartment->images[0]->filename)) ?
                                                  $apartment->getImgPath($apartment->images[0]->filename) :
                                                  Faker\Factory::create()->imageUrl($width = 640, $height = 480) }}" alt="">
                      </a>
                  </div>
                  <!-- Property Content -->
                  <div class="property-content">
                      <div class="ribbon ribbon-top-left">
                          <span>{{ $apartment->status }}</span>
                      </div>
                      <div class="other-top">
                          <p class="top-amb">{{ $apartment->rooms }} amb.</p>
                          <div class="top-area">
                              @if($apartment->from_price)
                              <span>Desde </span>
                              @endif
                              USD <b>@convert($apartment->price)</b>
                          </div>
                      </div>
                      <div class="other-bot">
                          <p class="bot-status">{{ $apartment->title }}</p>
                      <p class="bot-address">{{ $apartment->address }}, {{ $apartment->location }}</p>
                      </div>
                  </div>
              </div>
          </div>
        </div>
      @empty
      <div class="row">
        <div class="col-12 col-md-6 col-xl-4">
        </div>
      </div>
      @endforelse
  </div>
</section> --}}
@if($apartments)
    <section id="real-estate" class="featured-properties-area section-padding-0-50">
        <div class="container-fluid px-5">
            <div class="row">

                {{-- Apartment box --}}
                @foreach ($apartments as $apartment)
                    @include('apartment.box', $apartment)
                @endforeach
            </div>
            <div class="row pull-right paginadoHome">
                <div class="col-lg-1">{{ $apartments->links() }}</div>
            </div>
        </div>
    </section>
@endif


@include('partials.front-footer')

@endsection

resources/views/real-estate/top-menu.blade.php
    <div class="main-header-area" id="stickyHeader">
        <div class="classy-nav-container breakpoint-off">
            <!-- Classy Menu -->
            <div class="head-title">Propiedades</div>
            <nav class="classy-navbar justify-content-between" id="southNav">

                <!-- Logo -->
                <a class="nav-brand" href="{{ route('home.index') }}"><img src="{{ asset('img/core-img/logo.png') }}" alt=""></a>

                <!-- Navbar Toggler -->
                <div class="classy-navbar-toggler">
                    <img class="link menu" src="{{ asset('img/core-img/icMenu.png') }}" alt="">
                </div>

                <!-- Menu -->
                <div class="classy-menu">

                    <!-- close btn -->
                    <div class="classycloseIcon">
                        <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                    </div>

                    <!-- Nav Start -->
                    <div class="classynav">
                        <ul id="desktop-nav">
                            <li><a href="{{ route('home.index')  }}#apartments">Propiedades</a></li>
                            <li class="{{ Request::segment(1)=== 'investments' ? 'active' : '' }}"><a
                                    href="{{ route('investments.index') }}">Inversiones</a></li>
                            <li class="{{ Request::segment(1)=== 'appraisals' ? 'active' : '' }}"><a
                                    href="{{ route('appraisals.index') }}">Tasaciones</a></li>
                            <li class="{{ Request::segment(1)=== 'credits' ? 'active' : '' }}"><a
                                    href="{{ route('credits.index') }}">Crédito</a></li>
                            <li class="{{ Request::segment(1)=== 'credits' ? 'active' : '' }}"><a
                                    href="{{ route('articles.index',['section'=> 'real-estate']) }}">Prensa</a></li>
                            <li class="{{ Request::segment(1)=== 'contact' ? 'active' : '' }}"><a
                                    href="{{ route('contact.index') }}">
                                    <img class="link" src="{{ asset('img/core-img/icContacto.png') }}" alt="">
                                </a></li>


                            <li class="nav-item dropdown">
                                <a class="nav-link dropdo wn-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    {{-- <span><i class="fa fa-bars"></i></span> --}}
                                    <img class="link menu" src="{{ asset('img/core-img/icMenu.png') }}" alt="">
                                    <div class="dropdown-menu py-2" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item my-2 aMenuMobile"
                                            href="{{ route('nosotros.index')  }}">Nosotros</a>
                                        <a class="dropdown-item my-2 aMenuMobile"
                                            href="{{ route('home.index')  }}#real-estate_featured">Propiedades<br>Destacadas</a>
                                        <a class="dropdown-item my-2 aMenuMobile"
                                            href="{{ route('home.index')  }}#real-estate">Propiedades</a>
                                        <a class="dropdown-item my-2 aMenuMobile"
                                            href="{{ route('credits.index') }}">Crédito<br>Hipotecario</a>
                                        <a class="dropdown-item my-2 aMenuMobile"
                                            href="{{ route('credits.index') }}">Financiación</a>
                                        <a class="dropdown-item my-2 aMenuMobile"
                                            href="{{ route('contact.index') }}">Contacto</a>
                                    </div>
                                </a>
                            </li>
                        </ul>

                        <ul id="mobile-nav">
                            <li><a href="{{ route('home.index')  }}#apartments">Propiedades</a></li>
                            <li><a href="{{ route('investments.index') }}">Inversiones</a></li>
                            <li><a href="{{ route('appraisals.index') }}">Tasaciones</a></li>
                            <li><a href="{{ route('credits.index') }}">Crédito</a></li>
                            {{-- <li><a href="{{ route('articles.index',['section'=> 'real-estate']) }}">Prensa</a></li> --}}
                            <li><a href="{{ route('contact.index') }}">Contacto</i></a></li>
                            <li><a href="{{ route('nosotros.index')  }}">Nosotros</a></li>
                            <li><a href="{{ route('home.index')  }}#real-estate">Propiedades</a></li>
                            <li><a href="{{ route('home.index')  }}#real-estate_featured">Destacados</a></li>
                        </ul>

                    </div>
                    <!-- Nav End -->
                </div>
            </nav>
        </div>
    </div>